version: "3.8"

services:
  app:
    build: .
    container_name: gobarber_api
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: docker
      REDIS_HOST: db_redis
    volumes:
      - .:/usr/app
    depends_on: 
      - db_postgres
      - db_redis
    links:
      - db_postgres
      - db_redis

  db_postgres:
    image: postgres
    container_name: postgres_db_gobarber
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: gobarber
      POSTGRES_DB: gobarber_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres
    
  db_redis:
    image: redis:alpine
    container_name: redis_db_gobarber
    ports:
      - "6379:6379"

volumes:
  pgdata:
    driver: local

