# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Install Dependecies
        run: yarn
        
      - name: Build
        run: yarn build
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules"
          target: "~/app/gobarber-backend"
          
      - name: Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/gobarber-backend
            yarn
            ./node_modules/.bin/typeorm migration run
            pm2 restart server
